name: Build production resources
on: [push]
jobs:
  Build-Resources:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run prod
      - run: |
          git config --global user.name 'Simon Hamp'
          git config --global user.email 'simon.hamp@me.com'
          git add resources/dist/*
          git commit -m "Build resources"
          git push
